spring.application.name=testassessment
spring.datasource.url=jdbc:postgresql://localhost:5432/java-backend-test
spring.datasource.username=naufalirfann
spring.datasource.password=6991211
spring.jpa.hibernate.ddl-auto=update